const PENDING = "PENDING_";
const FULFILLED = "FULFILLED_";
const FAILED = "FAILED_";

const GET_TODO_LIST = "GET_TODO_LIST";
const CREATE_NEW_LIST = "CREATE_NEW_LIST";
const REMOVE_TODO_LIST = "REMOVE_TODO_LIST";
const GET_LIST_BY_ID = "GET_LIST_BY_ID";
const EDIT_TODO = "EDIT_TODO";

export {
  PENDING,
  FULFILLED,
  FAILED,

  GET_TODO_LIST,
  CREATE_NEW_LIST,
  REMOVE_TODO_LIST,
  GET_LIST_BY_ID,
  EDIT_TODO
}